name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.PROD_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to production server
        env:
          PROD_USER: ${{ secrets.PROD_USER }}
          PROD_HOST: ${{ secrets.PROD_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          # Copie des fichiers sur le serveur
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            ./ $PROD_USER@$PROD_HOST:$DEPLOY_PATH

          # Connexion SSH et déploiement
          ssh $PROD_USER@$PROD_HOST "cd $DEPLOY_PATH && \
            # Copie du fichier .env de production
            cp .env.production .env && \
            # Construction et redémarrage des conteneurs
            docker compose down && \
            docker compose up -d --build" 